"""Unify the raw datasets into a single cleaned JSONL corpus.

Unified schema (one JSON object per line):
    id          str   "<source>:<original id>"
    source      str   bangla-math | ganit
    question    str   problem statement (Bangla, may contain LaTeX)
    cot         str   step-by-step solution (Bangla for Ganit, English for Bangla-Math)
    answer      str   final answer, ASCII digits, no thousands separators
    difficulty  str   easy|medium|hard|olympiad (Ganit only, else "unknown")

Splits written to data/processed/:
    train.jsonl  - Bangla-Math train + Ganit SFT train, minus val carve-out
    val.jsonl    - 5% random carve-out of the train pool (seed 42)
    test.jsonl   - Ganit dev split (776 problems, difficulty-stratified), held out

A markdown stats report is written to docs/data_report.md.
"""

from __future__ import annotations

import json
import random
import re
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "data" / "raw"
OUT = ROOT / "data" / "processed"
DOCS = ROOT / "docs"

BN_DIGITS = str.maketrans("০১২৩৪৫৬৭৮৯", "0123456789")

ANSWER_TAG = re.compile(r"<answer>(.*?)</answer>", re.DOTALL)
THINK_TAG = re.compile(r"</?think>")


def norm_answer(raw: object) -> str:
    """Normalize a final answer: Bengali->ASCII digits, strip separators/space."""
    s = str(raw).translate(BN_DIGITS).strip()
    s = s.replace(",", "").replace("৳", "").strip()  # thousands sep, taka sign
    return s


def load_bangla_math() -> list[dict]:
    df = pd.read_parquet(RAW / "bangla_math_train.parquet")
    rows = []
    for r in df.itertuples():
        rows.append(
            {
                "id": f"bangla-math:{r.ID}",
                "source": "bangla-math",
                "question": str(r.Problem).strip(),
                "cot": str(r.COT).strip(),
                "answer": norm_answer(r.Answer),
                "difficulty": "unknown",
            }
        )
    return rows


def ganit_row(r, split: str) -> dict:
    # Full reasoning lives in the assistant message; strip <think>/<answer> markup.
    cot = ""
    for m in r.messages:
        if m["role"] == "assistant":
            cot = m["content"]
            break
    cot = THINK_TAG.sub("", ANSWER_TAG.sub("", cot)).strip()
    return {
        "id": f"ganit-{split}:{r.id}",
        "source": "ganit",
        "question": str(r.problem).strip(),
        "cot": cot,
        "answer": norm_answer(r.english_solution),
        "difficulty": str(r.difficulty),
    }


def load_ganit(filename: str, split: str) -> list[dict]:
    df = pd.read_parquet(RAW / filename)
    return [ganit_row(r, split) for r in df.itertuples()]


def clean(
    rows: list[dict], seen_questions: set[str], require_cot: bool = True
) -> tuple[list[dict], dict]:
    """Drop empty/duplicate questions and empty answers; report what was dropped."""
    kept, dropped = [], {"empty_question": 0, "empty_answer": 0, "empty_cot": 0, "duplicate": 0}
    for row in rows:
        if not row["question"]:
            dropped["empty_question"] += 1
        elif not row["answer"] or row["answer"].lower() in {"nan", "none"}:
            dropped["empty_answer"] += 1
        elif require_cot and not row["cot"]:
            dropped["empty_cot"] += 1
        elif row["question"] in seen_questions:
            dropped["duplicate"] += 1
        else:
            seen_questions.add(row["question"])
            kept.append(row)
    return kept, dropped


def write_jsonl(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    DOCS.mkdir(exist_ok=True)

    seen: set[str] = set()
    # Test set first so its questions also deduplicate the train pool
    # (leakage guard: identical problems must never appear in both).
    # Eval sets have no assistant CoT — only question + answer are required.
    test, d_test = clean(load_ganit("ganit_dev.parquet", "dev"), seen, require_cot=False)
    pool_raw = load_bangla_math() + load_ganit("ganit_sft_train.parquet", "sft")
    pool, d_pool = clean(pool_raw, seen)

    random.Random(42).shuffle(pool)
    n_val = int(len(pool) * 0.05)
    val, train = pool[:n_val], pool[n_val:]

    write_jsonl(OUT / "train.jsonl", train)
    write_jsonl(OUT / "val.jsonl", val)
    write_jsonl(OUT / "test.jsonl", test)

    def dist(rows: list[dict], key: str) -> dict:
        out: dict[str, int] = {}
        for row in rows:
            out[row[key]] = out.get(row[key], 0) + 1
        return dict(sorted(out.items()))

    numeric = sum(
        1 for row in train if re.fullmatch(r"-?\d+(\.\d+)?", row["answer"])
    )
    report = f"""# Data report

Generated by `src/data/preprocess.py`.

## Splits

| Split | Rows | Source |
|---|---:|---|
| train | {len(train)} | Bangla-Math + Ganit SFT (dedup, minus val) |
| val   | {len(val)} | 5% carve-out of train pool (seed 42) |
| test  | {len(test)} | Ganit dev (held out, difficulty-stratified) |

## Dropped during cleaning

- test: {d_test}
- train pool: {d_pool}

## Train composition

- by source: {dist(train, "source")}
- by difficulty: {dist(train, "difficulty")}
- purely numeric answers: {numeric}/{len(train)} ({numeric / len(train):.1%})

## Test composition

- by difficulty: {dist(test, "difficulty")}

## Schema

`id, source, question, cot, answer (ASCII digits), difficulty` — one JSON per line.
Ganit CoT is Bangla (from assistant `<think>` traces); Bangla-Math CoT is English.
"""
    (DOCS / "data_report.md").write_text(report, encoding="utf-8")
    print(report)


if __name__ == "__main__":
    main()
